version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/inventory
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - server_node_modules:/app/node_modules
      - ./server:/app        # you can remove this in pure-production

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000   # for `next build`
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000   # for runtime fetches
    ports:
      - "3000:3000"
    # In prod, you can comment these out to let Next serve its own build:
    volumes:
      - client_node_modules:/app/node_modules
      # - ./client/src:/app/src
      # - ./client/public:/app/public

volumes:
  db_data:
  server_node_modules:
  client_node_modules:
